# Generated by Django 3.0.7 on 2022-08-11 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audiomedia', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Audios',
            },
        ),
    ]
